wandb_version: 1

batch_size:
  value: 32
classifier_dropout:
  value: 0.3
clip_grad:
  value: false
epochs:
  value: 2
frac:
  value: 1
learning_rate:
  value: 3.0e-05
max_length:
  value: 64
optimizer:
  value: adam
perc_warmup_steps:
  value: 0
split_size:
  value: 0.2
