wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.16.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1652922553
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      3:
      - 2
      - 16
      4: 3.9.7
      5: 0.12.11
      6: 4.16.2
      8:
      - 1
      - 5
add_more_targets:
  desc: null
  value: false
batch_size:
  desc: null
  value: 32
classifier_dropout:
  desc: null
  value: 0.3
clip_grad:
  desc: null
  value: false
complex_graph:
  desc: null
  value: true
epochs:
  desc: null
  value: 3
frac:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 5.0e-05
max_length:
  desc: null
  value: 128
method:
  desc: null
  value: grid
metric:
  desc: null
  value:
    goal: maximize
    name: val_acc
optimizer:
  desc: null
  value: adam
parameters:
  desc: null
  value:
    add_more_targets:
      value: false
    batch_size:
      value: 32
    classifier_dropout:
      value: 0.3
    clip_grad:
      value: false
    complex_graph:
      values:
      - true
      - false
    epochs:
      value: 3
    frac:
      value: 1.0
    learning_rate:
      value: 5.0e-05
    max_length:
      value: 128
    optimizer:
      value: adam
    perc_warmup_steps:
      value: 0.1
    split_size:
      value: 0.2
perc_warmup_steps:
  desc: null
  value: 0.1
split_size:
  desc: null
  value: 0.2
