wandb_version: 1

add_more_targets:
  value: false
batch_size:
  value: 32
classifier_dropout:
  value: 0.3
clip_grad:
  value: false
complex_graph:
  value: true
epochs:
  value: 3
frac:
  value: 1
learning_rate:
  value: 5.0e-05
max_length:
  value: 128
optimizer:
  value: adam
perc_warmup_steps:
  value: 0.1
split_size:
  value: 0.2
